buildscript {
    repositories {
        mavenLocal()
        mavenCentral()
    }
    dependencies {
        classpath "org.openapitools:openapi-generator-gradle-plugin:7.13.0"
    }
}

plugins {
	id 'java'
	id 'org.springframework.boot' version '4.0.0-M3'
	id 'io.spring.dependency-management' version '1.1.7'
	id 'org.asciidoctor.jvm.convert' version '4.0.5'
	id 'com.github.ben-manes.versions' version '0.53.0'
	id 'jacoco'
}

group = 'com.obsidianforge'
version = '0.0.1-SNAPSHOT'
description = 'The Tabletop Simulator APIs'

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(21)
	}
}

configurations {
	compileOnly {
		extendsFrom annotationProcessor
	}
}

repositories {
	mavenCentral()
	maven { url = 'https://repo.spring.io/snapshot' }
}

ext {
	set('springCloudVersion', "2025.1.0-M4")
}

dependencies {
	implementation 'org.springframework.boot:spring-boot-starter-actuator'
	implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
	implementation 'org.springframework.boot:spring-boot-starter-jdbc'
	implementation 'org.springframework.boot:spring-boot-starter-liquibase'
	implementation 'org.springframework.boot:spring-boot-starter-security'
	implementation 'org.springframework.boot:spring-boot-starter-webflux'
	implementation 'org.springframework.boot:spring-boot-starter-websocket'
    implementation "org.springdoc:springdoc-openapi-starter-webmvc-ui:2.1.0"

	compileOnly 'org.projectlombok:lombok'
	
	developmentOnly 'org.springframework.boot:spring-boot-docker-compose'
	
	runtimeOnly 'com.h2database:h2'
	runtimeOnly 'org.postgresql:postgresql'
	
	annotationProcessor 'org.projectlombok:lombok'
	
	testImplementation 'org.springframework.boot:spring-boot-starter-test'
	testImplementation 'io.projectreactor:reactor-test'
	testImplementation 'org.springframework.cloud:spring-cloud-starter-contract-stub-runner'
	testImplementation 'org.springframework.graphql:spring-graphql-test'
	testImplementation 'org.springframework.security:spring-security-test'
	
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
	
	configurations.all {
        exclude group: 'org.slf4j', module: 'slf4j-simple'
    }
}

dependencyManagement {
	imports {
		mavenBom "org.springframework.cloud:spring-cloud-dependencies:${springCloudVersion}"
	}
}

apply plugin: "org.openapi.generator"

openApiGenerate {
    generatorName.set("spring")
    inputSpec.set("$rootDir/src/main/resources/api-spec.yaml".toString())
    outputDir.set("$buildDir/generated".toString())
    apiPackage.set("com.obsidianforge.tts.api")
    modelPackage.set("com.obsidianforge.tts.model")
    configOptions.set([
            dateLibrary         : "java8",
            library              : "spring-boot",
            reactive             : "false",
            useBeanValidation    : "true",
            delegatePattern      : "true",
            performBeanValidation: "true",
            interfaceOnly       : "false",
            useSpringBoot3      : "true",
            useSwaggerUI        : "true"
    ])
}

compileJava.dependsOn tasks.named("openApiGenerate")

tasks.named('test') {
	useJUnitPlatform()
}
