spring:
  application:
    name: Obsidian Forge Tabletop APIs
  cassandra:
    enabled: false
  liquibase:
    enabled: false
  management:
    endpoints:
      web:
        exposure:
          include: health,info,metrics,env, openapi, swagger-ui
    metrics:
      export:
        otlp:
          enabled: false
  logging:
    level:
      root: INFO
      com.obsidianforge.tabletopapis: DEBUG
      org.springframework.web: DEBUG
      org.springframework.http: DEBUG

